### ISSUE TITLE
Should it be `<` in Amdahl’s law?

### ISSUE THREAD

**Issue by YurongYou** [dbindel/cs5220-f20#1]
Hi David,

I was watching your lecture and it looks great in reveal.js! I guess [here](https://github.com/dbindel/cs5220-f20/blob/3c02f279bfe3d11dc2efed0f709a8ab6d11c92ba/web/lec/2020-09-03-overview.html#L558) might be a typo in Amdahl's law: `<` instead of `>`?

Best,
Yurong

**Comment by dbindel** [comment]
Thanks, you are correct!  Just pushed a fix.
